MvcWebApi.MvcClient/Models/EmployeeInfo.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace MvcWebApi.MvcClient.Models
{
    public class EmployeeInfo
    {
        [Key]
        public int EmpNo { get; set; }

        [DisplayName("Employee Name")]
        [Required(ErrorMessage = "Employee name most be filled.")]
        [StringLength(250,MinimumLength = 5,ErrorMessage = "Employee name most be between {1} charecters and {2} charecters.")]
        public string EmpName { get; set; }
        public decimal Salary { get; set; }

        [DisplayName("Department Name")]
        [Required(ErrorMessage = "Department name most be filled.")]
        [StringLength(250, MinimumLength = 5, ErrorMessage = "department most be between {1} charecters and {2} charecters.")]
        public string DeptName { get; set; }

        [DisplayName("Designation")]
        [Required(ErrorMessage = "Designation name most be filled.")]
        [StringLength(250, MinimumLength = 5, ErrorMessage = "Designation most be between {1} charecters and {2} charecters.")]
        public string Designation { get; set; }
    }
}

MvcWebApi.MvcClient/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web.Mvc;
using MvcWebApi.MvcClient.Models;
using Newtonsoft.Json;

namespace MvcWebApi.MvcClient.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly HttpClient client;
        private const string url = "http://localhost:52002/api/Employee";
        public EmployeeController()
        {
            client = new HttpClient {BaseAddress = new Uri(url)};
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }
        // GET: Employee
        public async Task<ActionResult> Index()
        {
            var httpResponseMessage = await client.GetAsync(url);
            if (httpResponseMessage.IsSuccessStatusCode)
            {
                var result = httpResponseMessage.Content.ReadAsStringAsync().Result;
                var employees = JsonConvert.DeserializeObject<List<EmployeeInfo>>(result);
                return View(employees);
            }
            return View("Error");
        }

        [HttpPost]
        public async Task<ActionResult> Index(string department)
        {
            var httpResponseMessage = await client.GetAsync(url);
            if (httpResponseMessage.IsSuccessStatusCode)
            {
                var result = httpResponseMessage.Content.ReadAsStringAsync().Result;                
                var employees = JsonConvert.DeserializeObject<List<EmployeeInfo>>(result);
                var departments = employees.Where(e => e.DeptName.Contains(department)).Select(e => e.DeptName).Distinct().ToList();
                return Json(departments,JsonRequestBehavior.AllowGet);
            }
            return View("Error");
        }
        public ActionResult Create()
        {
            return View(new EmployeeInfo());
        }

        //The Post method
        [HttpPost]
        public async Task<ActionResult> Create(EmployeeInfo Emp)
        {
            if (!ModelState.IsValid)
                return View(Emp);
            HttpResponseMessage responseMessage = await client.PostAsJsonAsync(url, Emp);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View("Error");
        }
        public async Task<ActionResult> Edit(int id)
        {
            HttpResponseMessage responseMessage = await client.GetAsync(url + "/" + id);
            if (responseMessage.IsSuccessStatusCode)
            {
                var responseData = responseMessage.Content.ReadAsStringAsync().Result;

                var Employee = JsonConvert.DeserializeObject<EmployeeInfo>(responseData);

                return View(Employee);
            }
            return View("Error");
        }

        //The PUT Method
        [HttpPost]
        public async Task<ActionResult> Edit(int id, EmployeeInfo Emp)
        {

            HttpResponseMessage responseMessage = await client.PutAsJsonAsync(url + "/" + id, Emp);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View("Error");
        }

        public async Task<ActionResult> Details(int id)
        {
            HttpResponseMessage responseMessage = await client.GetAsync(url + "/" + id);
            if (responseMessage.IsSuccessStatusCode)
            {
                var responseData = responseMessage.Content.ReadAsStringAsync().Result;

                var Employee = JsonConvert.DeserializeObject<EmployeeInfo>(responseData);

                return PartialView("_Details",Employee);
            }
            return View("Error");
        }
        public async Task<ActionResult> Delete(int id)
        {
            HttpResponseMessage responseMessage = await client.GetAsync(url + "/" + id);
            if (responseMessage.IsSuccessStatusCode)
            {
                var responseData = responseMessage.Content.ReadAsStringAsync().Result;

                var Employee = JsonConvert.DeserializeObject<EmployeeInfo>(responseData);

                return View(Employee);
            }
            return View("Error");
        }

        //The DELETE method
        [HttpPost]
        public async Task<ActionResult> Delete(int id, EmployeeInfo Emp)
        {

            HttpResponseMessage responseMessage = await client.DeleteAsync(url + "/" + id);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View("Error");
        }
    }
}

MvcWebApi.MvcClient/Views/Employee/Create.cshtml
@model MvcWebApi.MvcClient.Models.EmployeeInfo

@{
    ViewBag.Title = "Create";
}
<div class="container">
    <div class="panel panel-primary">
        <div class="panel-heading">Create New Employee</div>
        <div class="panel-body">
            <div class="row">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new {@class = "text-danger"})                       
                        <div class="form-group">
                            @Html.LabelFor(model => model.EmpName, htmlAttributes: new {@class = "control-label col-md-2"})
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.EmpName, new {htmlAttributes = new {@class = "form-control"}})
                                @Html.ValidationMessageFor(model => model.EmpName, "", new {@class = "text-danger"})
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Salary, htmlAttributes: new {@class = "control-label col-md-2"})
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Salary, new {htmlAttributes = new {@class = "form-control"}})
                                @Html.ValidationMessageFor(model => model.Salary, "", new {@class = "text-danger"})
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.DeptName, htmlAttributes: new {@class = "control-label col-md-2"})
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.DeptName, new {htmlAttributes = new {@class = "form-control"}})
                                @Html.ValidationMessageFor(model => model.DeptName, "", new {@class = "text-danger"})
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Designation, htmlAttributes: new {@class = "control-label col-md-2"})
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Designation, new {htmlAttributes = new {@class = "form-control"}})
                                @Html.ValidationMessageFor(model => model.Designation, "", new {@class = "text-danger"})
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <button type="submit" class="btn btn-primary btn-sm">
                                    <i class="glyphicon glyphicon-floppy-save"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
        <div class="panel-footer">
            <a href="@Url.Action("Index","Employee")" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-arrow-left"></i></a>
        </div>
    </div>
</div>

MvcWebApi.MvcClient/Views/Employee/Delete.cshtml
@model MvcWebApi.MvcClient.Models.EmployeeInfo

@{
    ViewBag.Title = "Delete";
}
<div class="container">
    <div class="panel panel-danger">
        <div class="panel-heading">Are you sure you want to delete this?</div>
        <div class="panel-body">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.EmpNo)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.EmpNo)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.EmpName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.EmpName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Salary)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Salary)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DeptName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DeptName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Designation)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Designation)
                </dd>
            </dl>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="form-actions no-color">
                    <button type="submit" class="btn btn-danger btn-sm">
                        <i class="glyphicon glyphicon-trash"></i>
                    </button>
                </div>
            }
        </div>
        <div class="panel-footer">
            <a href="@Url.Action("Index","Employee")" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-arrow-left"></i></a>
        </div>
    </div>
</div>

MvcWebApi.MvcClient/Views/Employee/Edit.cshtml
@model MvcWebApi.MvcClient.Models.EmployeeInfo

@{
    ViewBag.Title = "Edit";
}
<div class="container">
    <div class="panel panel-warning">
        <div class="panel-heading">Edit Employee</div>
        <div class="panel-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new {@class = "text-danger"})
                    <div class="form-group">
                        @Html.LabelFor(model => model.EmpNo, htmlAttributes: new {@class = "control-label col-md-2"})
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.EmpNo, new {htmlAttributes = new {@class = "form-control"}})
                            @Html.ValidationMessageFor(model => model.EmpNo, "", new {@class = "text-danger"})
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.EmpName, htmlAttributes: new {@class = "control-label col-md-2"})
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.EmpName, new {htmlAttributes = new {@class = "form-control"}})
                            @Html.ValidationMessageFor(model => model.EmpName, "", new {@class = "text-danger"})
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Salary, htmlAttributes: new {@class = "control-label col-md-2"})
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Salary, new {htmlAttributes = new {@class = "form-control"}})
                            @Html.ValidationMessageFor(model => model.Salary, "", new {@class = "text-danger"})
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.DeptName, htmlAttributes: new {@class = "control-label col-md-2"})
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DeptName, new {htmlAttributes = new {@class = "form-control"}})
                            @Html.ValidationMessageFor(model => model.DeptName, "", new {@class = "text-danger"})
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Designation, htmlAttributes: new {@class = "control-label col-md-2"})
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Designation, new {htmlAttributes = new {@class = "form-control"}})
                            @Html.ValidationMessageFor(model => model.Designation, "", new {@class = "text-danger"})
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <button type="submit" class="btn btn-warning btn-sm">
                                <i class="glyphicon glyphicon-floppy-save"></i>
                            </button>
                        </div>
                    </div>
                </div>
            }
        </div>
        <div class="panel-footer">
            <a href="@Url.Action("Index","Employee")" class="btn btn-sm btn-warning"><i class="glyphicon glyphicon-arrow-left"></i></a>
        </div>
    </div>
</div>

MvcWebApi.MvcClient/Views/Employee/Index.cshtml
@using System.Web.Mvc.Html
@model IEnumerable<MvcWebApi.MvcClient.Models.EmployeeInfo>
@{
    ViewBag.Title = "Index";
}
<div class="container">
    <div class="btn-group btn-group-sm">
        <a href="@Url.Action("Create", "Employee")" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-plus-sign"></i></a>
    </div>
    <div class="panel panel-info">
        <div class="panel-heading">Employees
            <div class="pull-right">
                <div class="btn-group btn-group-sm">
                    <a href="#" id="btnSearch" class="btn btn-xs">
                        <i class="glyphicon glyphicon-filter"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <div class="row">
                <table class="table table-bordered table-condensed table-hover">
                    <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.EmpName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Salary)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.DeptName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Designation)
                        </th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.EmpName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Salary)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DeptName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Designation)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new {id = item.EmpNo}) |
                                @*@Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |*@
                                <a href="javascript:void(0);" class="anchorDetail" data-id="@item.EmpNo">Details</a> |
                                @Html.ActionLink("Delete", "Delete", new {id = item.EmpNo})
                            </td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>

        </div>
    </div>
    <div id='details' class='modal'>
        <div class="modal-dialog">
            <div class="modal-content">
                <div id='detailsModalContent'></div>
            </div>
        </div>
    </div>
    <div class="modal fade danger" id="search" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="pull-right">
                        <button data-dismiss="modal" type="button" class="close" title="Close">x</button>
                    </div>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <h4 class="modal-title text-info">Search Employees Based on Department</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="form-horizontal">
                            @Html.Label("searchInput", "Search",new {@class="control-label col-sm-2"})
                            <div class="col-sm-10">
                                @Html.TextBox("searchInput","",new {@class="form-control"})
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button id="btnOK" type="button" value="Trash" class="btn btn-primary btn-xs" title="Search">
                        <i class="glyphicon glyphicon glyphicon-search"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts
{
    <script type="text/javascript">
        $(document).ready(function() {
            $('.anchorDetail').on('click', function() {
                var $buttonClick = $(this);
                var id = $buttonClick.attr('data-id');
                var options = { "backdrop": "static", keyboard: true };
                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("Details", "Employee")',
                    data: { "id": id },
                    success: function(data) {
                        $('#detailsModalContent').html(data);
                        $('#details').modal(options);
                        $('#details').modal('show');
                    },
                    error: function() {
                        alert("Dynamic content load failed.");
                    }
                });
            });
            $("#closbtn").click(function() {
                $('#details').modal('hide');
            });
            $('#btnSearch').on('click', function() {
                $('#search').modal('show');
            });
            //$('#searchInput').on('keypress', function() {
            //    alert($('#searchInput').val());
            //});
            $('#searchInput').autocomplete({
                source: function(request, response) {
                    $.ajax({
                        type: 'POST',
                        url: '@Url.Action("Index", "Employee")',
                        datatype: 'JSON',
                        data: { department: $('#searchInput').val() },
                        success: function(data) {
                            response($.map(data, function(item) {
                                return { label: item, value: item };
                            }));
                        }
                    });
                },
                messages: {
                    noResults: "",
                    results: ""
                }
            });
        });
    </script>
}

MvcWebApi.MvcClient/Views/Employee/_Details.cshtml
@model MvcWebApi.MvcClient.Models.EmployeeInfo
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
    <h4 class="modal-title" id="myModalLabel">EmployeeInfo</h4>
</div>
<div>    
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EmpName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmpName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeptName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeptName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Designation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Designation)
        </dd>

    </dl>
</div>

MvcWebApi.MvcClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    @*<link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />*@
    <link href="~/Content/bootstrap-yeti.min.css" rel="stylesheet" />
    @*<link href="~/Content/bootstrap-lumen.min.css" rel="stylesheet" />*@
    @*<link href="~/Content/bootstrap-united.min.css" rel="stylesheet" />*@
    <link rel="stylesheet" href="~/Content/themes/smoothness/jquery-ui-1.8.23.custom.css"> 
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Web Api in Mvc", "Index", "Employee", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()       
    </div>

    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.8.23.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>